### ISSUE TITLE
Here are some Helium Installation Issues and Feature Requests on iOS 15.0 for iPhone 11

### ISSUE THREAD

**Issue by gsons** [leminlimez/Helium#15]
### When installing Helium 1.1 on my iPhone 11 with the iOS 15.0 system, I encountered some issues:

1. The remaining battery percentage cannot display the "%" character.
2. When the background is white, it is difficult to see clearly due to the white font. Can the font color be automatically adjusted to white or black based on the background color?
3. When displaying network speed, the large notch on the iPhone 11 prevents the display of too much text. Can the option to remove the network speed icon or reduce the font size be considered to fully show the network speed?
4. Is it possible to add a feature for customizing the display of VPN status information?
Thank you!

![image](https://github.com/leminlimez/Helium/assets/15610655/473a270b-c606-48ff-a596-2455617f7599)

**Comment by leminlimez** [comment]
most of these are fixed

4. was mentioned in #29 so i will close this one but keep that one open
