### ISSUE TITLE
How can I remove duplicate display label

### ISSUE THREAD

**Issue by lyuxxx** [leminlimez/Helium#17]
There are two date labels in my status bar.I can confirm they are all come from Helium.Maybe it is a version issue?Reset button in Helium cannot solve this,can you help me?Thanks in advance.
![D5B85C64-F593-4B0C-8102-5DDBE1A750C3](https://github.com/leminlimez/Helium/assets/19743675/727b2432-3c00-4380-9779-a730dacc3805)

**Comment by leftshine** [comment]
respring or reboot may clear

**Comment by lyuxxx** [comment]
Reboot can solve this,respring can not.Thank you.
