### ISSUE TITLE
12pm 15.4.1 not working

### ISSUE THREAD

**Issue by RatedR9** [leminlimez/Helium#3]
after choose the style.enable uhd but not working.nothing show

**Comment by leminlimez** [comment]
fixed in v1.1

**Comment by RatedR9** [comment]
Thank you for your excellent work. can you add the  feature to change the display color ?

**Comment by leminlimez** [comment]
planned for next big update

**Comment by RatedR9** [comment]
Can you also add an always restart feature that restarts when it stop?
