### ISSUE TITLE
Adaptive foreground color

### ISSUE THREAD

**Issue by Lessica** [leminlimez/Helium#30]
Hello everyone, I'm the author of [TrollSpeed](https://github.com/Lessica/TrollSpeed).

I opened an issue here to share my progress on adaptive foregound color without the injection into SpringBoard.

I looked into **FrontBoardServices**, but failed to find a way to get the foreground color of the status bar...  
Now I made another attempt: using `CABackdropLayer` and `CAFilter` to achieve this.

(Not very perfect, use with caution.)
See: https://github.com/Lessica/TrollSpeed/commit/7e798f089ecee8a4aa243e7775c16d98b6319b10

**Comment by leminlimez** [comment]
thanks for sharing! I was looking to see if it would be a notification sent by the system that could be monitored.

I also tried adding your changes to keep the hud running in the background longer, but it ended up causing more issues so idk what went wrong.

**Comment by gsons** [comment]
> Hello everyone, I'm the author of [TrollSpeed](https://github.com/Lessica/TrollSpeed).
> 
> I opened an issue here to share my progress on adaptive foregound color without the injection into SpringBoard.
> 
> I looked into **FrontBoardServices**, but failed to find a way to get the foreground color of the status bar... Now I made another attempt: using `CABackdropLayer` and `CAFilter` to achieve this.
> 
> (Not very perfect, use with caution.) See: [Lessica/TrollSpeed@7e798f0](https://github.com/Lessica/TrollSpeed/commit/7e798f089ecee8a4aa243e7775c16d98b6319b10)

Great, in which version will you update this feature?

**Comment by Lessica** [comment]
> Thanks for sharing! I was looking to see if it would be a notification posted by the springboard that could be monitored.

I did not find any status bar style changed notification posted by SpringBoard.

Here are some more findings:
1. "user interface style is light" != "status bar tint color is white"
2. "app preferred status bar style" != "global status bar style"
3. Status bar is held by SpringBoard, not app.
4. Status bar is related to window scene management.

> I also tried adding your changes to keep the hud running in the background longer, but it ended up causing more issues (ie. not coming back after disappearing on the lock screen)

1. Root privilege is still required to avoid being killed on iOS 16 or above (I once removed that root privilege but proved to be wrong).
2. `memorystatus_control` **makes the situation even worse**.
3. Keys `UIApplicationShowsViewsWhileLocked/UIApplicationSystemWindowsSecureKey` make some scene on iOS 15.

See: https://github.com/Lessica/TrollSpeed/issues/11

**Comment by Lessica** [comment]
> > Hello everyone, I'm the author of [TrollSpeed](https://github.com/Lessica/TrollSpeed).
> > I opened an issue here to share my progress on adaptive foregound color without the injection into SpringBoard.
> > I looked into **FrontBoardServices**, but failed to find a way to get the foreground color of the status bar... Now I made another attempt: using `CABackdropLayer` and `CAFilter` to achieve this.
> > (Not very perfect, use with caution.) See: [Lessica/TrollSpeed@7e798f0](https://github.com/Lessica/TrollSpeed/commit/7e798f089ecee8a4aa243e7775c16d98b6319b10)
> 
> Great, in which version will you update this feature?

TrollSpeed will never add features other than "network speed monitor" and "HUD floating window". I think this feature is better for Helium.

**Comment by leminlimez** [comment]
completed in v2.2
