### ISSUE TITLE
Can't get url schemes to work

### ISSUE THREAD

**Issue by theoccurrence** [leminlimez/Helium#35]
Executing helium://toggle or one of the other commands with Safari or the Shortcuts app fails. I get an error stating I don't have an app called Helium installed on my device.

![image](https://github.com/leminlimez/Helium/assets/16444679/dc7f38c5-1bcc-49b9-944d-e21f4f43afa9)

iPhone 12 Pro Max, iOS 16.4, installed Helium with Trollstore

**Comment by theoccurrence** [comment]
On further inspection Helium doesn't seem to even have url schemes?

**Comment by leminlimez** [comment]
already got it fixed for next update

**Comment by huyhuyvu01** [comment]
> Executing helium://toggle or one of the other commands with Safari or the Shortcuts app fails. I get an error stating I don't have an app called Helium installed on my device.
> 
> ![image](https://private-user-images.githubusercontent.com/16444679/292789314-dc7f38c5-1bcc-49b9-944d-e21f4f43afa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNTY2MDgsIm5iZiI6MTcwNDI1NjMwOCwicGF0aCI6Ii8xNjQ0NDY3OS8yOTI3ODkzMTQtZGM3ZjM4YzUtMWJjYy00OWI5LTk0NGQtZTIxZjRmNDNhZmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA0MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZjE2OTBkNDg0OWM3ZGM3MTA5ZjZmYjY3MWQ4Mjc3MzdmYWJhY2I0MzVkZmUzM2ZlY2NjNGM1YWM3ZTYzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vEjj6V_BJN9i89NX3_WDYXGNxlnCLg08AKI6DDekBQA)
> 
> iPhone 12 Pro Max, iOS 16.4, installed Helium with Trollstore

Not related to the subject, but can i ask what font is it you are using? It look really nice

**Comment by theoccurrence** [comment]
> Not related to the subject, but can i ask what font is it you are using? It look really nice

Sorry for the late answer. I'm using Rhino 85%

**Comment by leminlimez** [comment]
fixed, sorry it took so long
