### ISSUE TITLE
[Bug] "Hide when Rotating" toggle is behaving opposite of what it's saying

### ISSUE THREAD

**Issue by yur1xpp** [leminlimez/Helium#47]
Toggling on the switch doing the opposite of what it's saying: So turn on will not hide them in landscape and vice-versa. I think the switch either did an opposite behavior, or the label of the switch is incorrect.

![PNG image 4](https://github.com/leminlimez/Helium/assets/34767893/f5bf628c-5fe8-4de6-be85-015c5ebe3592)

**Comment by udevsharold** [comment]
Actually, I found out that it's a (UI) bug! Toggling the switch on actually did the opposite. So turn the switch on won't hide in landscape, but turning them off will hide it. I think either the label or the behavior is reversed.

**Comment by leminlimez** [comment]
fixed
